# HATD3 算法配置文件。
seed:
  # 是否使用指定的随机种子
  seed_specify: True
  # 随机种子
  seed: 1
device:
  # 是否使用 CUDA
  cuda: True
  # 是否设置 CUDA 确定性模式
  cuda_deterministic: True
  # torch.set_num_threads 的参数
  torch_threads: 4
train:
  # 训练数据收集的并行环境数
  n_rollout_threads: 10
  # 总训练步数
  num_env_steps: 10000000
  # 预热步数
  warmup_steps: 10000
  # 每次训练的步数
  train_interval: 50
  # 训练迭代次数与 train_interval 的比率
  update_per_train: 1
  # 日志记录间隔（当前未使用）
  log_interval: ~
  # 评估间隔
  eval_interval: 10000
  # 是否使用线性学习率衰减
  use_linear_lr_decay: False
  # 回合结束时是否区分截断和终止
  use_proper_time_limits: True
  # 若设置则从该目录加载模型，否则随机初始化
  model_dir: ~
eval:
  # 是否启用评估
  use_eval: True
  # 评估的并行环境数
  n_eval_rollout_threads: 20
  # 每次评估的回合数
  eval_episodes: 40
render:
  # 是否启用渲染
  use_render: False
  # 渲染的回合数
  render_episodes: 10
model:
  # 网络参数
  # 网络中 MLP 模块的隐藏层大小
  hidden_sizes: [128, 128]
  # 激活函数，可选 sigmoid, tanh, relu, leaky_relu, selu
  activation_func: relu
  # 最终激活函数，可选 sigmoid, tanh, relu, leaky_relu, selu
  final_activation_func: tanh
  # 优化器参数
  # Actor 学习率
  lr: 0.0005
  # Critic 学习率
  critic_lr: 0.001
algo:
  # 折扣因子
  gamma: 0.99
  # 离策略经验回放缓冲区大小
  buffer_size: 1000000
  # 训练批次大小
  batch_size: 1000
  # 目标模型软更新系数
  polyak: 0.005
  # 探索噪声
  expl_noise: 0.1
  # 目标策略平滑噪声
  policy_noise: 0.2
  # 目标策略平滑噪声上限
  noise_clip: 0.5
  # 策略更新频率
  policy_freq: 2
  # 前瞻步数
  n_step: 1
  # 是否在 Actor 之间共享参数
  share_param: False
  # 是否使用固定优化顺序
  fixed_order: False
logger:
  # 日志目录
  log_dir: "./results"
